- name: Profile Readme Development Stats
  uses: anmol098/waka-readme-stats@V1.1
  with:
    GH_TOKEN: ${{ secrets.GH_TOKEN }} # default is ${{ github.token }}
    WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
    SHOW_OS: "True" 
    SHOW_PROJECTS: "False"
    SHOW_EDITORS: "True" 
    SHOW_TIMEZONE: "True" 
    SHOW_COMMIT: "True" 
    SHOW_LANGUAGE: "True" 
    SHOW_LINES_OF_CODE: "True" 
    SHOW_LANGUAGE_PER_REPO: "True" 
    SHOW_LOC_CHART: "True" 
    SHOW_DAYS_OF_WEEK: "True" 
