name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '0 9 * * *'

jobs:
  update-readme:
    name: Update waka metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "True"
        

#       - uses: anmol098/waka-readme-stats@master
#         with:
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
#           GH_TOKEN: ${{ secrets.GH_TOKEN }} 
#           SHOW_OS: "True" 
#           SHOW_PROJECTS: "False"
#           SHOW_EDITORS: "True" 
#           SHOW_TIMEZONE: "True" 
#           SHOW_COMMIT: "True" 
#           SHOW_LANGUAGE: "True" 
#           SHOW_LINES_OF_CODE: "True" 
#           SHOW_LANGUAGE_PER_REPO: "True" 
#           SHOW_LOC_CHART: "True" 
#           SHOW_DAYS_OF_WEEK: "True" 
        

