name: Waka Detailed Statistics
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  update-readme:
    name: Update Readme Detailed Statistics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
        
